Provable Events
proto-kit/framework pull request #185
Opened 2024-07-26 09:38 UTC by ejMina226

2024-09-10 12:44 UTC, rpanic requested changes
good job!

2024-09-10 12:44 UTC, rpanic commented on packages/module/src/method/runtimeMethod.ts
> +  return events
We already have a abstraction for this sort of behaviour, that I kept from you. It's called `DefaultProvableHashList`

2024-09-10 12:44 UTC, rpanic commented on packages/persistance/src/services/prisma/mappers/EventMapper.ts
> +        Field.fromJSON(field as string)
Field(field)

2024-09-10 12:44 UTC, rpanic commented on packages/persistance/test-integration/utils.ts
> +  public events = {
I forgot to also change that along with my changes, need to be changed as well pls :)

2024-09-10 12:44 UTC, rpanic commented on packages/sequencer/test/integration/BlockProduction.test.ts
> +  public events = {
Same here :/

2024-09-17 07:36 UTC, ejMina226 commented on packages/persistance/src/services/prisma/mappers/EventMapper.ts
> +        Field.fromJSON(field as string)
Typescript is complaining with this change, saying 
`Argument of type 'JsonValue' is not assignable to parameter of type 'string | number | bigint | Field | FieldConst | FieldVar'.
  Type 'null' is not assignable to type 'string | number | bigint | Field | FieldConst | FieldVar'.t`

2024-09-17 08:56 UTC, ejMina226 commented on packages/module/src/method/runtimeMethod.ts
> +  return events
It's not clear to me that this is relevant. We could have different event types in the list of events and therefore we will need to create different instances of each DefaultProvableHashList, right? Or have I misunderstood? Thanks.

2024-09-17 09:08 UTC, ejMina226 commented on packages/module/src/method/runtimeMethod.ts
> +  return events
If we can just reuse the same ProvableType then we can do: 
`  const hashList = new DefaultProvableHashList(events[0].eventType);
  events.forEach((event) => {
    hashList.push(event.event);
  });
  return hashList.commitment; `

2024-09-17 11:12 UTC, ejMina226 commented on packages/persistance/test-integration/utils.ts
> +  public events = {
I've updated the test to reflect the new format. However, there appears to be a linting error here
`  public events = new RuntimeEvents({
    test: TestEvent,
  });`

The error is: `Unsafe assignment of an error typed value.`

2024-09-17 11:33 UTC, ejMina226 commented on packages/module/src/runtime/RuntimeModule.ts
> +    condition: emitIfConditional,
@rpanic I've added in an implementation of the emitIf.

2024-09-19 12:27 UTC, ejMina226 commented on packages/module/src/method/runtimeMethod.ts
> +  return events
Resolved in Slack thread.

2024-09-24 06:41 UTC, rpanic commented on packages/persistance/src/services/prisma/mappers/EventMapper.ts
> +        Field.fromJSON(field as string)
Okay then let's leave it, they should be semantically the same anyways

2024-09-24 07:08 UTC, rpanic approved these changes

2024-09-24 07:08 UTC, rpanic commented on packages/module/test/runtimeMethod.test.ts
> +    expect(eventsHash).toStrictEqual(
Thing here is that toEventsHash has to respect the condition on it's own, because in-circuit we will call toEventsHash with all events every time. We implement that correctly, but the test should also reflect that, i.e. we should feed in all 3 events here

2024-09-24 07:08 UTC, rpanic commented on packages/module/src/runtime/RuntimeModule.ts
> +    eventName: Key,
As discussed, lets make the condition the first argument

2024-09-24 07:35 UTC, merged